### ISSUE TITLE
load_script() doesn't get currect JS url with non-standard composer vendor-dir

### ISSUE THREAD

**Issue by herrschuessler** [afragen/wp-dismiss-notice#1]
The `load_script`function doesn't account for non-standard composer vendor directories which can be set in the composer.json config file:

```
{
    "config": {
        "vendor-dir": "xyz/vendor"
    },
}
```

Instead it still returns the path `/vendor/afragen/wp-dismiss-notice/js/dismiss-notice.js` which leads to a 404 for the JS file.

**Comment by afragen** [comment]
Unless there is some way to get a composer variable within the PHP code I don't think it'll work.

Do you have any ideas?

**Comment by afragen** [comment]
Fixed in https://github.com/afragen/wp-dismiss-notice/commit/d6511c4eea243449dc6d15efcc807aa8ab0d3a91

Added a filter `dismiss_notice_vendor_dir` to modify for non-standard directory.
